image: public.ecr.aws/docker/library/python:slim-bullseye
inline_script:
- |+
  cat > /tmp/engine.json <<EOF
  {
    "model": "/fsx/pretrained-models/deepseek-ai/DeepSeek-R1",
    "tokenizer": "/fsx/pretrained-models/deepseek-ai/DeepSeek-R1",
    "enable_log_requests": false,
    "gpu_memory_utilization": 0.95,
    "dtype": "auto",
    "enforce_eager": true,
    "tensor_parallel_size": 8,
    "pipeline_parallel_size": 4,
    "max_num_seqs": 2,
    "max_model_len": 81920
  }

  EOF
pre_script:
  - mkdir -p $CONFIG_ROOT
  - cp /tmp/engine.json $CONFIG_ROOT/engine.json
process:
  env:
    - name: CONFIG_ROOT
      value: /efs/home/{{ .Release.Name }}/config