---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: MPIJob
    plural: mpijobs
    shortNames:
    - mj
    - mpij
    singular: mpijob
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: Either `gpus` or `replicas` should be specified, but not both
          oneOf:
          - properties:
              gpus:
                description: Valid values are 1, 2, 4, or any multiple of 8
                oneOf:
                - enum:
                  - 1
                  - 2
                  - 4
                  type: integer
                - minimum: 8
                  multipleOf: 8
                  type: integer
                title: Total number of GPUs
            required:
            - gpus
          - properties:
              replicas:
                description: The GPU resource limit should be specified for each replica
                minimum: 1
                title: Total number of replicas
                type: integer
            required:
            - replicas
          title: The MPIJob spec
  version: v1alpha1
