image: public.ecr.aws/docker/library/python:slim-bullseye
inline_script:
- |+
  cat > /tmp/engine.json <<EOF
  {
    "model": "/fsx/pretrained-models/meta-llama/Llama-3.3-70B-Instruct",
    "tokenizer": "/fsx/pretrained-models/meta-llama/Llama-3.3-70B-Instruct",
    "enable_log_requests": false,
    "tensor_parallel_size": 8,
    "pipeline_parallel_size": 2,
    "device_type": "cuda"
  }

  EOF
pre_script:
  - mkdir -p $CONFIG_ROOT
  - cp /tmp/engine.json $CONFIG_ROOT/engine.json
process:
  env:
    - name: CONFIG_ROOT
      value: /efs/home/{{ .Release.Name }}/config
