apiVersion: v1
kind: Pod
metadata:
  name: attach-pvc
spec:
  containers:
  - name: attach-pvc
    image: ubuntu:latest
    command: ["/bin/bash"]
    securityContext:
      privileged: true
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 3600; done"]
    volumeMounts:
    - name:  efs 
      mountPath: /efs
  volumes:
  - name:  efs
    persistentVolumeClaim:
      claimName: pv-efs # k8s persistent-volume-claim name
