apiVersion: v1
kind: Pod
metadata:
  name: attach-pvc
spec:
  containers:
  - name: attach-pvc
    image: ubuntu:latest
    command: ["/bin/bash"]
    securityContext:
      privileged: true
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 3600; done"]
    volumeMounts:
    - name:  efs # efs or fsx 
      mountPath: /efs # /efs or /fsx
  volumes:
  - name:  efs # efs or fsx 
    persistentVolumeClaim:
      claimName: tensorpack-efs-gp-bursting # k8s persistent-volume-claim name
