---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stage-data 
data:
  stage-data.sh: |
    aws s3 cp --recursive s3://$S3_BUCKET/$S3_PREFIX $STAGE_DIR
---
apiVersion: v1
kind: Pod
metadata:
  name: stage-data 
spec:
  restartPolicy: Never
  volumes:
  - name: efs # efs, or fsx
    persistentVolumeClaim:
      claimName: tensorpack-efs-gp-bursting # persistent volume claim name 
  - name: config
    configMap:
      defaultMode: 420
      items:
      - key: stage-data.sh
        mode: 365
        path: stage-data.sh
      name: stage-data 
  containers:
  - name: stage-data
    env:
    - name: S3_BUCKET
      value: my-bucket 
    - name: S3_PREFIX
      value: mask-rcnn/eks/input 
    - name: STAGE_DIR 
      value: /efs # /efs or /fsx
    command:
    -  sh 
    - /etc/config/stage-data.sh
    image: # use image with aws cli support  
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/config
      name: config
    - mountPath: /efs # /efs or /fsx
      name: efs # efs, or fsx
