# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Tri-state for ServiceMonitor creation (metricsService.enabled):
#   null  = auto-detect via .Capabilities (works with helm install/upgrade)
#   true  = always create (use with helm template / GitOps)
#   false = never create (opt-out even if prometheus-operator is installed)
{{- $serviceMonitorEnabled := false }}
{{- if kindIs "invalid" .Values.metricsService.enabled }}
  {{- $serviceMonitorEnabled = (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
{{- else }}
  {{- $serviceMonitorEnabled = .Values.metricsService.enabled }}
{{- end }}
{{- if $serviceMonitorEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dynamo-operator.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.metricsService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "dynamo-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "dynamo-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    scheme: https
    path: /metrics
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
{{- end }}
