apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: triton-lws-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-triton-lws-pod-reader
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: triton-lws-pod-reader
  apiGroup: rbac.authorization.k8s.io