apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.fsx.volume_name | default "pv-fsx" }}
spec:
  capacity:
    storage: {{ .Values.fsx.storage | default "1200Gi" }} 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.fsx.class_name | default "fsx-sc" }}
  csi:
    driver: fsx.csi.aws.com
    volumeHandle:  {{ .Values.fsx.fs_id }}
    volumeAttributes:
      dnsname: {{ .Values.fsx.dns_name }}
      mountname: {{ .Values.fsx.mount_name }}