apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume_name | default "pv-fsx" }}
spec:
  capacity:
    storage: 1200Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - noatime
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.class_name | default "fsx-sc" }}
  csi:
    driver: fsx.csi.aws.com
    volumeHandle:  {{ .Values.fs_id }}
    volumeAttributes:
      dnsname: {{ .Values.dns_name }}
      mountname: {{ .Values.mount_name }}