apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fsx.claim_name | default "pv-fsx" }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.fsx.class_name | default "fsx-sc" }}
  volumeName: {{ .Values.fsx.volume_name | default "pv-fsx" }}
  resources:
    requests:
      storage: {{ .Values.fsx.storage | default "1200Gi" }} 