apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.efs.volume_name | default "pv-efs" }}
spec:
  capacity:
    storage: {{ .Values.efs.storage | default "1000Gi" }}  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.efs.class_name | default "efs-sc" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.efs.fs_id }}