apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.efs.claim_name | default "pv-efs" }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.efs.class_name | default "efs-sc" }}
  volumeName: {{ .Values.efs.volume_name | default "pv-efs" }}
  resources:
    requests:
      storage: {{ .Values.efs.storage | default "1000Gi" }} 