apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claim_name | default "pv-efs" }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.class_name | default "efs-sc" }}
  volumeName: {{ .Values.volume_name | default "pv-efs" }}
  resources:
    requests:
      storage: 100Gi